<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>McManager.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="McManager.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\tests\fixtures\game-metadata\mojang-version-manifest-v2.json">
      <LogicalName>McManager.Core.Setup.mojang-version-manifest-v2.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\tests\fixtures\game-metadata\paper-fill-v3-project.json">
      <LogicalName>McManager.Core.Setup.paper-fill-v3-project.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\docs\modrinth-exclude-include.json">
      <LogicalName>McManager.Core.Setup.modrinth-exclude-include.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\docs\cf-exclude-include.json">
      <LogicalName>McManager.Core.Setup.cf-exclude-include.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Setup\pack-lists\mcmgr-exclude-include.json">
      <LogicalName>McManager.Core.Setup.mcmgr-exclude-include.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\server-icons\default-icon.png">
      <LogicalName>McManager.Core.ServerIcons.default-icon.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\server-icons\overlay-offline.png">
      <LogicalName>McManager.Core.ServerIcons.overlay-offline.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\server-icons\overlay-starting.png">
      <LogicalName>McManager.Core.ServerIcons.overlay-starting.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\assets\server-icons\overlay-unavailable.png">
      <LogicalName>McManager.Core.ServerIcons.overlay-unavailable.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OCI.DotNetSDK.Artifacts" Version="144.0.0" />
    <PackageReference Include="OCI.DotNetSDK.Common" Version="144.0.0" />
    <PackageReference Include="OCI.DotNetSDK.Core" Version="144.0.0" />
    <PackageReference Include="OCI.DotNetSDK.Events" Version="144.0.0" />
    <PackageReference Include="OCI.DotNetSDK.Functions" Version="144.0.0" />
    <PackageReference Include="OCI.DotNetSDK.Identity" Version="144.0.0" />
    <PackageReference Include="OCI.DotNetSDK.Objectstorage" Version="144.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.11" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
  </ItemGroup>

</Project>
