namespace McManager.Core.Setup;

/// <summary>
/// OpenTofu <c>prevent_destroy</c> on the product bucket is a literal (cannot be a variable).
/// Manager writes a gitignored module override only on the typed-confirm destroy path.
/// </summary>
public static class BucketDestroyOverride
{
    public const string FileName = "zz_mcmgr_destroy_override.tf";

    public static string PathFor(string infraDirectory) =>
        Path.Combine(infraDirectory, "modules", "storage", FileName);

    public static void Install(string infraDirectory)
    {
        var path = PathFor(infraDirectory);
        var dir = Path.GetDirectoryName(path);
        if (!string.IsNullOrWhiteSpace(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(path,
            """
            # Generated by McManager destroy. Gitignored (*_override.tf). Do not commit.
            resource "oci_objectstorage_bucket" "shared" {
              lifecycle {
                prevent_destroy = false
              }
            }

            """);
    }

    public static void Remove(string infraDirectory)
    {
        var path = PathFor(infraDirectory);
        if (File.Exists(path))
            File.Delete(path);
    }
}
