using McManager.Core.Config;
using McManager.Core.Services;

namespace McManager.Core.Setup;

/// <summary>Writes Setup variables to LocalAppData — never <c>infra/terraform.tfvars</c> in the repo.</summary>
public static class TfvarsWriter
{
    public static ServiceResult Write(TofuWorkspace workspace, SetupWizardState state, string functionImage = "")
    {
        try
        {
            Directory.CreateDirectory(workspace.RootDirectory);
            var tenancy = OciConfigProfiles.TryGetValue(state.OciProfile, "tenancy");
            if (ProductPaths.IsTofuDryRun()
                && (string.IsNullOrWhiteSpace(tenancy) || tenancy.Contains("REPLACE_ME", StringComparison.Ordinal)))
            {
                tenancy = "ocid1.tenancy.oc1..dryrunplaceholder000000000000000000000";
            }

            if (string.IsNullOrWhiteSpace(tenancy) || tenancy.Contains("REPLACE_ME", StringComparison.Ordinal))
            {
                return ServiceResult.Fail(
                    "Could not read tenancy= from ~/.oci/config for the selected profile.");
            }

            var cidr = NormalizeAdminCidr(state.AdminCidr);
            if (cidr is null)
                return ServiceResult.Fail("admin_cidr must be an IPv4 address or /32 CIDR.");

            if (!SshKeyHelper.LooksLikePublicKey(state.SshPublicKey))
                return ServiceResult.Fail("SSH public key is missing or invalid.");

            if (!Vm1ShapeChoice.IsAllowed(state.Vm1Ocpus, state.Vm1MemoryGb))
            {
                return ServiceResult.Fail(
                    "VM1 size must be 2 OCPU / 12 GB or 4 OCPU / 24 GB.");
            }

            var existing = state.CreateCompartment ? "" : state.ExistingCompartmentId.Trim();
            var body =
                $"# Generated by McManager Setup. Do not copy over repo infra/terraform.tfvars.\n"
                + $"tenancy_ocid            = {HclString(tenancy)}\n"
                + $"region                  = {HclString(state.OciRegion.Trim())}\n"
                + $"oci_profile             = {HclString(string.IsNullOrWhiteSpace(state.OciProfile) ? "DEFAULT" : state.OciProfile.Trim())}\n"
                + $"ssh_public_key          = {HclString(state.SshPublicKey.Trim())}\n"
                + $"admin_cidr              = {HclString(cidr)}\n"
                + $"admin_name              = {HclString("admin")}\n"
                + $"alert_email             = {HclString(state.AlertEmail.Trim())}\n"
                + $"compartment_name        = {HclString(string.IsNullOrWhiteSpace(state.CompartmentName) ? "mcmgr" : state.CompartmentName.Trim())}\n"
                + $"existing_compartment_id = {HclString(existing)}\n"
                + $"function_image          = {HclString(functionImage.Trim())}\n"
                + $"vm1_ocpus               = {state.Vm1Ocpus}\n"
                + $"vm1_memory_gb           = {state.Vm1MemoryGb}\n";

            File.WriteAllText(workspace.VarFilePath, body);
            return ServiceResult.Ok();
        }
        catch (Exception ex)
        {
            return ServiceResult.Fail($"Failed to write tfvars: {ex.Message}");
        }
    }

    public static string? NormalizeAdminCidr(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return null;
        var t = raw.Trim();
        if (t.EndsWith("/32", StringComparison.Ordinal))
            t = t[..^3];
        if (!FriendRules.TryNormalizeIp(t, out var ip))
            return null;
        return ip + "/32";
    }

    public static string HclString(string value)
    {
        var escaped = value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\r", "", StringComparison.Ordinal);
        return "\"" + escaped + "\"";
    }
}
