<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>McManager.PackTestHarness</RootNamespace>
    <AssemblyName>McManager.PackTestHarness</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\McManager.Core\McManager.Core.csproj" />
  </ItemGroup>

</Project>
